# Generated by Django 3.2 on 2023-04-28 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='user',
        ),
    ]
