# Generated by Django 4.2 on 2023-05-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browserGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-timestamp']},
        ),
    ]
